#!/bin/sh
#
# Start lvgl_user....
#


start() {
	printf "Starting lvgl_user main: "
	# echo -n -e '\e[?17;14;224c'
	echo 0 > /sys/class/graphics/fbcon/cursor_blink
	start-stop-daemon -S -q -m -b -p /var/run/lvgl_user.pid \
			-x /usr/share/lvgl_user/main
      [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping lvgl_user main: "
	start-stop-daemon -K -q -p /var/run/lvgl_user.pid \
			  -x /usr/share/lvgl_user/main
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
